### ISSUE TITLE
Add allow= option for iframes

### ISSUE THREAD

**Issue by carlmjohnson** [rdmurphy/frames#20]
See https://github.com/spotlightpa/viz-redistricting-2020/commit/21e52200130fcbb96adf6e2b5c79d73ed32166b5 and https://newsnerdery.slack.com/archives/C428T14TC/p1641225433058600

**Comment by rdmurphy** [comment]
We discussed this in NN Slack, but the probably "best" answer here is for me to get the `rework` branch live, which gives people full control over any and all attributes they'd like to set. I'll take a pass at that this week!

**Comment by carlmjohnson** [comment]
:+1:
