### ISSUE TITLE
broken unpkg for v1.0.0

### ISSUE THREAD

**Issue by SawyerClick** [rdmurphy/frames#22]
[v1.0.0](https://unpkg.com/@newswire/frames@1.0.0/dist/index.mjs)'s unkpg is showing up as blank. contradicting the docs. v0.3.1 is still showing up correctly in unpkg

**Comment by rdmurphy** [comment]
Ack, yeah — unpkg didn’t seem to like how I soft launched the `lastest` tag on npm.

When you go to this URL does it do the right thing?

https://unpkg.com/@newswire/frames

I also may just have incorrect URLs in the README now. 😅 I’ll check!

**Comment by SawyerClick** [comment]
ah, yep, there we go! 

looks like the readme links to `index.umd.js` (which was the file name in v0.3.1) file when it is actively located at `frames.umd.js` on unpkg.

**Comment by rdmurphy** [comment]
Yup, that was it! This is the URL you want: https://unpkg.com/@newswire/frames/dist/frames.umd.js

I updated this in the README as well! Thanks for the heads up.
