### ISSUE TITLE
Allow passing in of iframe title parameter

### ISSUE THREAD

**Issue by petulla** [rdmurphy/frames#5]
Ryan

Promise not to inundate you with requests. One nice accessibility feature pym had was the ability to pass in a config object with a `title` attribute when creating a new Pym frame. 

See [this](http://blog.apps.npr.org/pym.js/api/pym.js/1.3.2/module-pym.Parent.html) documentation. 

Any chance you could add a little of that sauce? Would keep us in an even accessibility baseline when switching over. Looks like you have the names attribute so this would follow the same pattern you've used.

**Comment by rdmurphy** [comment]
Addressed with the release of `@newswire/frames@0.3.1`. Good call! 👋
